default:
  navigation:
    - title: kuchina
      url: /t/furniture
      subtitle: Categories
      url: /t/furniture
      items:
        - :title: table
          :url: /t/furniture/tables
        - :title: stillages-and-consoles
          :url: /t/furniture/stillages-and-consoles
        - :title: armchairs
          :url: /t/furniture/armchairs
        - :title: chairs
          :url: /t/furniture/chairs
        - :title: bedside_cabinets
          :url: /t/furniture/bedside-cabinets

    - title: Łazienka
      url: /t/lights
      subtitle: Categories
      url: /t/lights
      
      items:
        - :title: Biuro
          :url: /t/lights/chandeliers
        - :title: table_lamp
          :url: /t/lights/table-lamp
        - :title: floor_lamp
          :url: /t/lights/floor-lamp
        - :title: sconces
          :url: /t/lights/sconces
        - :title: lampshade
          :url: /t/lights/lampshade
        - :title: bulbs
          :url: /t/lights/bulbs

    - title: Gastronomia
      url: /t/accessories

    - title: Ogród
      url: /t/accessories
    
    - title: Dom
      url: /t/accessories
    
    - title: Hale
      url: /t/accessories
    
    - title: Auto
      url: /t/accessories
    
    - title: Dezynfekcja
      url: /t/accessories

    - title: Ochrona
      url: /t/accessories

    - title: BHP
      url: /t/accessories



